version: 2.1
jobs:
  build:
    docker:
      - image: circleci/node:7.10
    working_directory: ~/repo
    branches:
      only:
        - master
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
            - v1-dependencies-
      - run: npm install
      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}
      - run:
          command: |
            [ -s "$HOME/.nvm/nvm.sh" ] && source "$HOME/.nvm/nvm.sh" && nvm use
            [ ! -d "node_modules" ] && npm install
            npm run generate
            gulp deploy
            ls -la
